# Generated by Django 3.1.2 on 2021-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateofbirth',
            field=models.DateField(verbose_name="patient's birth day"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name="patient's first name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="patient's last name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profileimage',
            field=models.ImageField(upload_to='images/patient/', verbose_name='Profile image'),
        ),
    ]
