# Generated by Django 3.1.2 on 2021-07-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210729_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patients Info'},
        ),
    ]
