# Generated by Django 3.1.2 on 2021-07-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210728_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_type',
            old_name='tye_name',
            new_name='type_name',
        ),
    ]
